trigger:
  - master
  - develop
  - release/*
pr:
  - master
  - develop
schedules:
- cron: "0 0 * * *"
  displayName: Daily build (UTC)
  branches:
    include:
    - master
    - develop

variables:
  jobuuid: $(Build.BuildId)$(Agent.Id)
  agent: ''
  key: '/tmp/id_rsa'
  cssh: 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i $(key)'
  dir: '/tmp/demo'

jobs:

  - template: templates/job.yaml
    parameters:
      name: bionic
      distro: $(gcp.vm.distro.bionic)
      repo: $(gcp.vm.repo.ubuntu)

  - template: templates/job.yaml
    parameters:
      name: xenial
      distro: $(gcp.vm.distro.xenial)
      repo: $(gcp.vm.repo.ubuntu)

  - template: templates/job.yaml
    parameters:
      name: buster
      distro: $(gcp.vm.distro.buster)
      repo: $(gcp.vm.repo.debian)

  - template: templates/job.yaml
    parameters:
      name: stretch
      distro: $(gcp.vm.distro.stretch)
      repo: $(gcp.vm.repo.debian)
  
  - template: templates/job.yaml
    parameters:
      name: centos8
      distro: $(gcp.vm.distro.centos8)
      repo: $(gcp.vm.repo.centos)