version: "3"
services:
    tutorial-init:
        build: ./init/tutorial
        container_name: tutorial-init
        depends_on:
            - iofog-controller
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - iofog-controller:iofog-controller
        network_mode: bridge
