name: tutorial
microservices:
- name: Sensors
  agent:
    name: local-agent
  config: {}
  images:
    x86: iofog/sensors:latest
    registry: remote
  volumes: []
  ports: []
  env: []
- name: Rest API
  agent:
    name: local-agent
  config: {}
  images:
    x86: iofog/freeboard-api:latest
    registry: remote
  volumes: []
  ports:
    - internal: 80
      external: 10101
  env: []
- name: Freeboard
  agent:
    name: local-agent
  config: {}
  images:
    x86: iofog/freeboard:latest
    registry: remote
  volumes: []
  ports:
    - internal: 80
      external: 10102
  env: []
routes:
- from: Sensors
  to: Rest API